name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMIT_PAT }}
          fetch-depth: 0

      - name: Yarn install
        run: yarn

      - name: Transform drinkit tokens
        run: yarn transform:drinkit

      - name: Transform dodo tokens
        run: yarn transform:dodo

      - name: Build package
        run: yarn build

      - name: Update version
        run: yarn version minor

      - name: Commit new versions
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            ci: Release package

            [skip ci]

      - name: Release package
        run: yarn npm publish

  notifications:
    name: Notifications
    runs-on: ubuntu-latest
    needs: [ publish ]
    if: always()
    env:
      COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}
    steps:
      - name: Notify success
        if: ${{ needs.publish.result == 'success' && github.ref == 'refs/heads/main'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *design-tokens-sample*
            
            Дизайнеры обновили токены - обновите пакетик
            
            [commit](${{ env.COMMIT_URL }})
      - name: Notify failure
        if: ${{ needs.publish.result == 'failure' && github.ref == 'refs/heads/main'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *design-tokens-sample*
            
            У дизайнеров что-то сломалось. Помогите им!
            
            [commit](${{ env.COMMIT_URL }})
